version: '3.8'

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql/
    networks:
      - wordpress
    ports:
      - 3306:3306
    restart: on-failure

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - wordpress:/var/www/html/wordpress
    env_file:
      - .env
    networks:
      - wordpress
    ports:
      - 9000:9000
    depends_on:
      - mariadb
    restart: on-failure

  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build: ./requirements/nginx
    volumes:
      - wordpress:/var/www/html/wordpress
    env_file:
      - .env
    networks:
      - wordpress
    ports:
      - 443:443
    restart: always
    init: true

networks:
  wordpress:
    name: wordpress
    driver: bridge

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/hamza/data/wordpress
    name: wordpress
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/hamza/data/mariadb
    name: mariadb
